# Top Level Types
type Query {
  # greeting: String
  job(id: ID!): Job
  company(id: ID!): Company
  jobs: [Job!]
}

type Mutation {
  createJob(input: CreateJobInput!): Job
  deleteJob(id: ID!): Job
}

# Job and Company Models
type Job {
  id: ID!
  company: Company!
  title: String!
  description: String
}

type Company {
  id: ID!
  name: String!
  description: String
  jobs: [Job!]
}

# Input Types
input CreateJobInput {
  title: String!
  companyId: ID!
  description: String
}
