type Query {
  # greeting: String
  job(id: ID!): Job
  company(id: ID!): Company
  jobs: [Job!]
}

type Job {
  id: ID!
  company: Company
  title: String!
  description: String
}

type Company {
  id: ID!
  name: String!
  description: String
}
